spring:
  application:
    name: user-service # Must match the filename in config-server/config/
  config:
    import: 'configserver:${CONFIG_SERVER_URI:http://config.platform:9000}'
  cloud:
    config:
      fail-fast: true
      uri: http://config.platform:9000
